import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/common/SideMenu";

const inter = Inter({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Olatilewa | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex gap-20`}>
        <SideMenu className="fixed left-0 top-0 h-full w-[50px]" />
        <main className="flex-1 ml-[70px]">{children}</main>
      </body>
    </html>
  );
}
